### ISSUE TITLE
LOGCAT

### ISSUE THREAD

**Issue by sajjadyousefnia** [SamaneYaghoobi/awesome-persian-youtubers#39]
https://www.youtube.com/channel/UCBM3dVa1OK3Mv2Mp2kbzdtA

https://irlogcat.ir/

**Comment by AmiiirCom** [comment]
> https://www.youtube.com/channel/UCBM3dVa1OK3Mv2Mp2kbzdtA
> 
> https://irlogcat.ir/


hey Sajjad, I will add your youtube channel and send PR :)

**Comment by AmiiirCom** [comment]
adding this channel to the list
