### ISSUE TITLE
awesome-persian-blogs !

### ISSUE THREAD

**Issue by amirbagh75** [SamaneYaghoobi/awesome-persian-youtubers#43]
اگر همچین پروژه ای برای وبلاگ های فارسی هم باشه خیلی خیلی خوب میشه! امثال من که وبلاگ دنبال میکنیم خیلی به کارمون میاد. من خودم میتونم یک لیست طویل برای init شدن تحویل بدم.

**Comment by ashkanRmk** [comment]
ایده خوبیه امیر اما وبلاگ فارسی تعدادشون خیلی خیلی زیاده و با اومدن ویرگول چندبرابر هم شده و سازماندهیشون خیلی سخت میشه و از یکجایی به بعد به خاطر طولانی شدن زیادی لیست و نداشتن فرایندی برای تشخیص معتبر و به روز نبودن بلاگ وجود نداره و اون اعتبار و کارکردش رو از دست میده


بازم اگر جور دیگه ای به ذهنت میرسه بگو

**Comment by ashkanRmk** [comment]
این ریپو هم نسبتن قدیمی هستش و خیلی به روز نیست
اما لیست بلندی داره
https://github.com/VahidN/IranianITBloggers

**Comment by amirbagh75** [comment]
> این ریپو هم نسبتن قدیمی هستش و خیلی به روز نیست
> اما لیست بلندی داره
> https://github.com/VahidN/IranianITBloggers

جالب بود این لیسته. مرسی اشکان
